spring:
  application:
    name: inventory-grpc-server

  datasource:
    url: jdbc:postgresql://localhost:5435/inventory_db
    username: inventory_db_user
    password: inventory_db_user_password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          fetch_size: 400
        generate_statistics: true
        format_sql: true
        default_schema: public

  flyway:
    schemas: public
    url: jdbc:postgresql://localhost:5435/inventory_db
    user: inventory_db_user
    password: inventory_db_user_password

  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        max.poll.records: 200
        fetch.max.wait.ms: 500
        fetch.min.bytes: 1
        max.poll.interval.ms: 300000
        session.timeout.ms: 15000
        heartbeat.interval.ms: 5000
      auto-offset-reset: earliest
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    listener:
      type: single
      ack-mode: record

grpc:
  port: 6568
  shutdownGrace: 30
  enable-reflection: true

equipment-kafka:
  topics: db.equipment.public.ammunition,db.equipment.public.attachment,db.equipment.public.grenade,db.equipment.public.gun
  group-id: inventory-equipment-consumer-test-8

players-kafka:
  topic: db.public.player
  group-id: inventory-player-message-consumer-test-2

market-kafka-product-trade-issue-required:
  topic: db.market.public.product_trade_issue_required_message_outbox
  group-id: inventory-product-trade-issue-required-message-consumer-test-7

reference-data-caching:
  data-page-size: 100
  refresh-rate-seconds: 600
  scheduled-refresh-cache-enabled: true

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true