syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.equipment.protobuf.grenade;

option java_multiple_files = true;

import "common/common.proto";

message GrenadeInfo {
  int32 id = 1;
  bool enabled = 2;
  string name = 3;
  int32 blast_damage_radius_meters = 4;
  int32 max_blast_damage_hp = 5;
  int32 max_blind_time_ms = 6;
  int32 max_deaf_time_ms = 7;
  int64 created_timestamp = 8;
  int64 updated_timestamp = 9;
}

message GrenadeInfoListPage {
  repeated GrenadeInfo data = 1;
  common.protobuf.PaginationInfo pagination_info = 2;
}

message GrenadeWritableData {
  bool enabled = 1;
  string name = 2;
  int32 blast_damage_radius_meters = 3;
  int32 max_blast_damage_hp = 4;
  int32 max_blind_time_ms = 5;
  int32 max_deaf_time_ms = 6;
}

message CreateGrenadeRequest {
  GrenadeWritableData data = 1;
}

message UpdateGrenadeRequest {
  int32 grenade_id = 1;
  GrenadeWritableData data = 2;
}

message GetGrenadeRequest {
  int32 grenade_id = 1;
}

message GetEnabledGrenadeRequest {
  int32 grenade_id = 1;
}

message GetGrenadesRequest {
  optional common.protobuf.PaginationRequest pagination_request = 1;
  optional GrenadesFilter filter = 2;
}

message GrenadesFilter {
  optional bool enabled = 1;
  optional string name = 2;
  repeated int32 grenade_ids = 3;
  optional int64 updated_after = 4;
}
