syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.inventory.protobuf.inventory.initial;

option java_multiple_files = true;

import "common/common.proto";
import "inventory/datatypes.proto";
import "equipment-shared-contract/contract.proto";

message InitialPlayerInventoryItemInfo {
  equipment.contract.EquipmentType equipmentType = 1;
  int32 equipmentId = 2;
  int32 amount = 3;
  bool enabled = 4;
  int64 created_timestamp = 5;
  int64 updated_timestamp = 6;
  int32 version = 7;
}

message InitialPlayerInventoryItemsPage {
  repeated InitialPlayerInventoryItemInfo data = 1;
  common.protobuf.PaginationInfo pagination_info = 2;
}

message GetInitialPlayerInventoryRequest {
  optional common.protobuf.PaginationRequest pagination_request = 1;
  optional Filter filter = 2;

  message Filter {
    optional bool enabled = 1;
  }
}

message SavedInitialPlayerInventoryItem {
  equipment.contract.EquipmentType equipment_type = 1;
  int32 equipment_id = 2;
  int32 amount = 3;
  bool enabled = 4;
  int32 version = 5;
}

message DeletedInitialPlayerInventoryItem {
  equipment.contract.EquipmentType equipment_type = 1;
  int32 equipment_id = 2;
}

message UpdateInitialPlayerInventoryRequest {
  repeated SavedInitialPlayerInventoryItem saved_items = 1;
  repeated DeletedInitialPlayerInventoryItem deleted_items = 2;
}