syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.market.protobuf.product;

option java_multiple_files = true;

import "common/common.proto";

enum ProductEquipmentType {
  UNKNOWN = 0;
  GUN = 1;
  GRENADE = 2;
  ATTACHMENT = 3;
  AMMUNITION = 4;
}

message ProductInfo {
  int32 id = 1;
  PriceInfo price = 2;
  ProductEquipmentInfo equipment = 3;
  bool enabled = 4;
  int64 createdTimestamp = 5;
  int64 updatedTimestamp = 6;
  int32 version = 7;
}

message PriceInfo {
  int32 currencyId = 1;
  int32 amount = 2;
}

message ProductEquipmentInfo {
  ProductEquipmentType type = 1;
  int32 id = 2;
  int32 amount = 3;
}

message ProductInfoListPage {
  repeated ProductInfo data = 1;
  common.protobuf.PaginationInfo paginationInfo = 2;
}

message GetProductRequest {
  int32 id = 1;
}

message GetProductsRequest {
  optional common.protobuf.PaginationRequest paginationRequest = 1;
  optional Filter filter = 2;

  message Filter {
    repeated int32 ids = 1;
    optional bool enabled = 2;
    repeated ProductEquipmentType equipmentTypes = 3;
    repeated int32 equipmentIds = 4;
    optional bool equipmentEnabled = 5;
    repeated int32 priceCurrencyIds = 6;
    optional bool priceCurrencyEnabled = 7;
    optional int32 priceLow = 8;
    optional int32 priceHigh = 9;
    optional int32 equipmentAmountLow = 10;
    optional int32 equipmentAmountHigh = 11;
  }
}

message CreateProductRequest {
  ProductWritableData data = 1;
}

message UpdateProductRequest {
  int32 productId = 1;
  int32 version = 2;
  ProductWritableData data = 3;
}

message ProductWritableData {
  ProductEquipmentInfo equipment = 1;
  PriceInfo price = 2;
  bool enabled = 3;
}