syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.market.protobuf.product;

option java_multiple_files = true;

import "common/common.proto";
import "equipment-shared-contract/contract.proto";

message ProductInfo {
  int32 id = 1;
  PriceInfo price = 2;
  ProductEquipmentInfo equipment = 3;
  bool enabled = 4;
  int64 created_timestamp = 5;
  int64 updated_timestamp = 6;
  int32 version = 7;
}

message PriceInfo {
  int32 currency_id = 1;
  int32 amount = 2;
}

message ProductEquipmentInfo {
  equipment.contract.EquipmentType  equipment_type = 1;
  int32 equipment_id = 2;
  int32 amount = 3;
}

message ProductInfoListPage {
  repeated ProductInfo data = 1;
  common.protobuf.PaginationInfo pagination_info = 2;
}

message GetProductRequest {
  int32 id = 1;
}

message GetProductsRequest {
  optional common.protobuf.PaginationRequest pagination_request = 1;
  optional Filter filter = 2;

  message Filter {
    optional bool enabled = 1;
    repeated equipment.contract.EquipmentType equipment_types = 2;
    optional bool equipment_enabled = 3;
    repeated int32 price_currency_ids = 4;
    optional bool price_currency_enabled = 5;
  }
}

message CreateProductRequest {
  ProductWritableData data = 1;
}

message UpdateProductRequest {
  int32 product_id = 1;
  int32 version = 2;
  ProductWritableData data = 3;
}

message ProductWritableData {
  ProductEquipmentInfo equipment = 1;
  PriceInfo price = 2;
  bool enabled = 3;
}
