syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.equipment.protobuf.grenade;

option java_multiple_files = true;

import "common.proto";

message GrenadeInfo {
  int32 id = 1;
  bool enabled = 2;
  string name = 3;
  int32 blastDamageRadiusMeters = 4;
  int32 maxBlastDamageHP = 5;
  int32 maxBlindTimeMs = 6;
  int32 maxDeafTimeMs = 7;
  int64 createdTimestamp = 8;
  int64 updatedTimestamp = 9;
}

message GrenadeInfoListPage {
  repeated GrenadeInfo data = 1;
  int64 totalCount = 2;
}

message GrenadeWritableData {
  bool enabled = 1;
  string name = 2;
  int32 blastDamageRadiusMeters = 3;
  int32 maxBlastDamageHP = 4;
  int32 maxBlindTimeMs = 5;
  int32 maxDeafTimeMs = 6;
}

message CreateGrenadeRequest {
  GrenadeWritableData data = 1;
}
message UpdateGrenadeRequest {
  int32 grenadeId = 1;
  GrenadeWritableData data = 2;
}

message GetGrenadeRequest {
  int32 grenadeId = 1;
}

message GetEnabledGrenadeRequest {
  int32 grenadeId = 1;
}

message GetGrenadesRequest {
  optional common.PaginationRequest paginationRequest = 1;
  optional GrenadesFilter filter = 2;
}

message GrenadesFilter {
  optional bool enabled = 1;
  optional string name = 2;
  repeated int32 grenadeId = 3;
}