syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.equipment.protobuf.currency;

option java_multiple_files = true;

import "common/common.proto";

message CurrencyInfo {
  int32 id = 1;
  bool enabled = 2;
  string name = 3;
  bool can_be_bought = 4;
  bool can_be_given_as_award = 5;
  int64 created_timestamp = 6;
  int64 updated_timestamp = 7;
}

message CurrencyInfoListPage {
  repeated CurrencyInfo data = 1;
  common.protobuf.PaginationInfo pagination_info = 2;
}

message CurrencyWritableData {
  bool enabled = 1;
  string name = 2;
  bool can_be_bought = 3;
  bool can_be_given_as_award = 4;
}

message CreateCurrencyRequest {
  CurrencyWritableData data = 1;
}

message UpdateCurrencyRequest {
  int32 currency_id = 1;
  CurrencyWritableData data = 2;
}

message GetEnabledCurrencyRequest {
  int32 currency_id = 1;
}

message GetCurrencyRequest {
  int32 currency_id = 1;
}

message GetCurrenciesRequest {
  optional common.protobuf.PaginationRequest pagination_request = 1;
  optional CurrenciesFilter filter = 2;
}

message CurrenciesFilter {
  optional bool enabled = 1;
  optional string name = 2;
  optional bool can_be_bought = 3;
  optional bool can_be_given_as_award = 4;
  repeated int32 currency_ids = 5;
  optional int64 updated_after = 6;
}
