syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.equipment.protobuf.currency;

option java_multiple_files = true;

import "common/common.proto";

message CurrencyInfo {
  int32 id = 1;
  bool enabled = 2;
  string name = 3;
  bool canBeBought = 4;
  bool canBeGivenAsAward = 5;
  int64 createdTimestamp = 6;
  int64 updatedTimestamp = 7;
}

message CurrencyInfoListPage {
  repeated CurrencyInfo data = 1;
  common.protobuf.PaginationInfo paginationInfo = 2;
}

message CurrencyWritableData {
  bool enabled = 1;
  string name = 2;
  bool canBeBought = 3;
  bool canBeGivenAsAward = 4;
}

message CreateCurrencyRequest {
  CurrencyWritableData data = 1;
}

message UpdateCurrencyRequest {
  int32 currencyId = 1;
  CurrencyWritableData data = 2;
}

message GetEnabledCurrencyRequest {
  int32 currencyId = 1;
}

message GetCurrencyRequest {
  int32 currencyId = 1;
}

message GetCurrenciesRequest {
  optional common.protobuf.PaginationRequest paginationRequest = 1;
  optional CurrenciesFilter filter = 2;
}

message CurrenciesFilter {
  optional bool enabled = 1;
  optional string name = 2;
  optional bool canBeBought = 3;
  optional bool canBeGivenAsAward = 4;
  repeated int32 currencyId = 5;
}