syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.market.protobuf.money.bundle;

option java_multiple_files = true;

import "market/money-bundle/datatypes.proto";
import "google/protobuf/empty.proto";

service MoneyBundleServiceAPI {
  rpc GetMoneyBundle(GetMoneyBundleRequest) returns (MoneyBundleInfo);
  rpc GetEnabledMoneyBundle(GetMoneyBundleRequest) returns (MoneyBundleInfo);
  rpc GetMoneyBundles(GetMoneyBundlesRequest) returns (MoneyBundleInfoListPage);
  rpc CreateMoneyBundle(CreateMoneyBundleRequest) returns (MoneyBundleInfo);
  rpc UpdateMoneyBundle(UpdateMoneyBundleRequest) returns (MoneyBundleInfo);
}