spring:
  application:
    name: market-grpc-server

  datasource:
    url: jdbc:postgresql://localhost:5436/market_db
    username: market_db_user
    password: market_db_user_password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          fetch_size: 400
        generate_statistics: false
        format_sql: true
        default_schema: public

  flyway:
    schemas: public
    url: jdbc:postgresql://localhost:5436/market_db
    user: market_db_user
    password: market_db_user_password

  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    listener:
      ack-mode: record

grpc:
  port: 6567
  shutdownGrace: 30
  enable-reflection: true

payment-stub-grpc:
  host: localhost
  port: 6568
  deadline-ms: 2000

payment-kafka:
  topic: db.payment.public.payment_processed_message_outbox
  group-id: market-payment-processed-message-consumer-test-3

# TODO SET NORMAL
reference-data-caching:
  data-page-size: 10
  refresh-rate-seconds: 200000
  scheduled-refresh-cache-enabled: true