spring:
  application:
    name: market-grpc-server

  datasource:
    url: jdbc:postgresql://localhost:5436/market_db
    username: market_db_user
    password: market_db_user_password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          fetch_size: 400
        generate_statistics: false
        format_sql: true
        default_schema: public

  flyway:
    schemas: public
    url: jdbc:postgresql://localhost:5436/market_db
    user: market_db_user
    password: market_db_user_password

grpc:
  port: 6567
  shutdownGrace: 30
  enable-reflection: true

# TODO SET NORMAL
reference-data-caching:
  data-page-size: 10
  refresh-rate-seconds: 200000
  scheduled-refresh-cache-enabled: true