spring:
  application:
    name: market-grpc-server

  datasource:
    url: jdbc:postgresql://localhost:5436/market_db
    username: market_db_user
    password: market_db_user_password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          fetch_size: 400
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        generate_statistics: false
        format_sql: true
        default_schema: public

  flyway:
    schemas: public
    url: jdbc:postgresql://localhost:5436/market_db
    user: market_db_user
    password: market_db_user_password

  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        max.poll.records: 200
        fetch.max.wait.ms: 500
        fetch.min.bytes: 1
        max.poll.interval.ms: 300000
        session.timeout.ms: 15000
        heartbeat.interval.ms: 5000
      auto-offset-reset: earliest
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    listener:
      type: single
      ack-mode: record

grpc:
  port: 6567
  shutdownGrace: 30
  enable-reflection: true

payment-stub-grpc:
  host: localhost
  port: 6569
  deadline-ms: 20000

equipment-kafka:
  topics: db.equipment.public.ammunition,db.equipment.public.attachment,db.equipment.public.grenade,db.equipment.public.gun
  group-id: market-equipment-consumer-test-2

currency-kafka:
  topic: db.equipment.public.currency
  group-id: market-equipment-currency-consumer-test-2

players-kafka:
  topic: db.public.player
  group-id: market-player-message-consumer-test-6

payment-kafka:
  topic: db.payment.public.payment_processed_message_outbox_v2
  group-id: market-payment-processed-message-consumer-test-6

inventory-product-trade-issuance-performed-kafka:
  topic: db.inventory.public.product_trade_issuance_performed_message_outbox
  group-id: inventory-product-trade-issuance-performed-message-consumer-test-1

reference-data-caching:
  data-page-size: 100
  refresh-rate-seconds: 600
  scheduled-refresh-cache-enabled: true

stuck-money-bundle-trade-processing:
  enabled: true
  period: 10s
  payment-creation-wait-processing:
    enabled: true
    max-stuck-period: 30s
  payment-pending-processing:
    enabled: true
    max-stuck-period: 30m