syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.players.protobuf;

option java_multiple_files = true;

import "shooter-players/common.proto";

message PlayerInfo {
  int32 playerId = 1;
  string email = 2;
  string firstName = 3;
  string lastName = 4;
  string login = 5;
  bool enabled = 6;
  int64 createdTimestamp = 7;
}

message PlayerInfoListPage {
  repeated PlayerInfo data = 1;
  int64 totalCount = 2;
}

message GetPlayersRequest {
  optional common.PaginationRequest paginationRequest = 1;
  optional PlayersFilter filter = 2;
}

message PlayersFilter {
  optional string login = 1;
  optional string email = 2;
  optional bool  enabled = 3;
  repeated int32 playerId = 4;
}

message GetPlayerRequest {
  int32 playerId = 1;
}