syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.players.protobuf;

option java_multiple_files = true;

import "common/common.proto";

message PlayerInfo {
  string player_uuid = 1;
  string email = 2;
  string first_name = 3;
  string last_name = 4;
  string login = 5;
  bool enabled = 6;
  int64 created_timestamp = 7;
}

message PlayerInfoListPage {
  repeated PlayerInfo data = 1;
  common.protobuf.PaginationInfo pagination_info = 2;
}

message GetPlayersRequest {
  optional common.protobuf.PaginationRequest pagination_request = 1;
  optional PlayersFilter filter = 2;
}

message PlayersFilter {
  optional string login = 1;
  optional string email = 2;
  optional bool  enabled = 3;
  repeated string player_uuids = 4;
}

message GetPlayerRequest {
  oneof field{
    string player_uuid = 1;
    string keycloak_id = 2;
  }
}