syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.equipment.protobuf.gun;

option java_multiple_files = true;

import "common.proto";
import "ammunition/imported_datatypes.proto";
import "attachment/imported_datatypes.proto";

enum GunType {
  PISTOL = 0;
  SUBMACHINE_GUN = 1;
  ASSAULT_RIFLE = 2;
  SCATTERSHOT = 3;
  MACHINE_GUN = 4;
  PRECISION_RIFLE = 5;
}

message GunInfo {
  int32 id = 1;
  bool enabled = 2;
  string name = 3;
  int32 weightGrams = 4;
  int32 rateOfFirePerMinute = 5;
  GunType type = 6;
  repeated ammunition.AmmunitionReducedInfo compatibleAmmunitionInfos = 7;
  repeated attachment.AttachmentReducedInfo compatibleAttachments = 8;
  int64 createdTimestamp = 9;
  int64 updatedTimestamp = 10;
}

message GunReducedInfo {
  int32 id = 1;
  bool enabled = 2;
  string name = 3;
  int32 weightGrams = 4;
  int32 rateOfFirePerMinute = 5;
  GunType type = 6;
}

message GunInfoListPage {
  repeated GunInfo data = 1;
  int64 totalCount = 2;
}

message GunWritableData {
  bool enabled = 1;
  string name = 2;
  GunType type = 3;
  int32 weightGrams = 4;
  int32 rateOfFirePerMinute = 5;
  repeated int32 compatibleAmmunitionIds = 6;
  repeated int32 compatibleAttachmentIds = 7;
}

message CreateGunRequest {
  GunWritableData data = 1;
}

message UpdateGunRequest {
  int32 gunId = 1;
  GunWritableData data = 2;
}

message GetGunRequest {
  int32 gunId = 1;
}

message GetEnabledGunRequest {
  int32 gunId = 1;
}

message GetGunsRequest {
  optional common.PaginationRequest paginationRequest = 1;
  optional GunsFilter filter = 2;
  optional common.RelatedEntitiesInclusionMode relatedEntitiesInclusionMode = 3;
}

message GunsFilter {
  optional bool enabled = 1;
  optional string name = 2;
  optional GunType type = 3;
  repeated int32 gunId = 4;
}