syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.market.protobuf.account;

option java_multiple_files = true;

import "common/common.proto";
import "market/trade/datatypes.proto";

message PlayerAccountItemInfo {
  int32 currencyId = 1;
  int32 amount = 2;
}

message PlayerAccountItemsPage {
  repeated PlayerAccountItemInfo data = 1;
  common.protobuf.PaginationInfo paginationInfo = 2;
}

message GetPlayerAccountRequest {
  optional common.protobuf.PaginationRequest paginationRequest = 1;
  int32 playerId = 2;
}

message InitializePlayerAccountRequest {
  int32 playerId = 1;
}

message PlayerCurrencyOperationRequest {
  int32 playerId = 1;
  int32 currencyId = 2;
  int32 amount = 3;
}

