syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.equipment.protobuf.attachment;

option java_multiple_files = true;

import "equipment/gun/datatypes.proto";
import "equipment/attachment/imported_datatypes.proto";
import "common/common.proto";

message AttachmentInfo {
  int32 id = 1;
  bool enabled = 2;
  string name = 3;
  AttachmentType type = 4;
  AttachmentEffect effect = 5;
  repeated gun.GunReducedInfo compatible_guns = 6;
  int64 created_timestamp = 7;
  int64 updated_timestamp = 8;
}

message AttachmentInfoListPage {
  repeated AttachmentInfo data = 1;
  common.protobuf.PaginationInfo pagination_info = 2;
}

message AttachmentWritableData {
  bool enabled = 1;
  string name = 2;
  AttachmentType type = 3;
  AttachmentEffect effect = 4;
  repeated int32 compatible_gun_ids = 5;
}

message CreateAttachmentRequest {
  AttachmentWritableData data = 1;
}

message UpdateAttachmentRequest {
  int32 attachment_id = 1;
  optional AttachmentWritableData data = 2;
}

message GetAttachmentRequest {
  int32 attachment_id = 1;
}

message GetEnabledAttachmentRequest {
  int32 attachment_id = 1;
}

message GetAttachmentsRequest {
  optional common.protobuf.PaginationRequest pagination_request = 1;
  optional AttachmentsFilter filter = 2;
  optional common.protobuf.RelatedEntitiesInclusionMode compatible_guns_inclusion_mode = 3;
}

message AttachmentsFilter {
  optional bool enabled = 1;
  optional string name = 2;
  optional AttachmentType type = 3;
  repeated int32 compatible_gun_ids = 4;
  optional bool only_enabled_compatible_guns = 5;
  repeated int32 attachment_ids = 6;
  optional int64 updated_after = 7;
}
