server:
  port: 8180

spring:
  application:
    name: api-gateway-player

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7777/realms/shooter-players

scheduling:
  pool-size: 5

caches:
  enabled: true
  currency:
    page-size: 100
    refresh-by-schedule-enabled: true
    refresh-interval-ms: 30000
  gun:
    page-size: 100
    refresh-by-schedule-enabled: true
    refresh-interval-ms: 30000
  grenade:
    page-size: 100
    refresh-by-schedule-enabled: true
    refresh-interval-ms: 30000
  ammunition:
    page-size: 100
    refresh-by-schedule-enabled: true
    refresh-interval-ms: 30000
  attachment:
    page-size: 100
    refresh-by-schedule-enabled: true
    refresh-interval-ms: 30000
  player:
    reset-by-schedule-enabled: true
    reset-interval-ms: 900000

player-grpc-service:
  server:
    host: localhost
    port: 6565
  deadline-ms: 10000
  retry:
    enabled: true
    max-attempts: 5
    initial-backoff: 0.2s
    max-backoff: 2s
    backoff-multiplier: 1.7
    retryable-status-codes:
      - UNAVAILABLE
      - RESOURCE_EXHAUSTED
      - DEADLINE_EXCEEDED
      - INTERNAL
    throttling:
      enabled: true
      max-tokens: 30
      token-ratio: 0.2

equipment-grpc-service:
  server:
    host: localhost
    port: 6566
  deadline-ms: 10000
  retry:
    enabled: true
    max-attempts: 5
    initial-backoff: 0.2s
    max-backoff: 2s
    backoff-multiplier: 1.7
    retryable-status-codes:
      - UNAVAILABLE
      - RESOURCE_EXHAUSTED
      - DEADLINE_EXCEEDED
      - INTERNAL
    throttling:
      enabled: true
      max-tokens: 30
      token-ratio: 0.2

market-grpc-service:
  server:
    host: localhost
    port: 6567
  deadline-ms: 10000
  retry:
    enabled: true
    max-attempts: 5
    initial-backoff: 0.2s
    max-backoff: 2s
    backoff-multiplier: 1.7
    retryable-status-codes:
      - UNAVAILABLE
      - RESOURCE_EXHAUSTED
      - DEADLINE_EXCEEDED
      - INTERNAL
    throttling:
      enabled: true
      max-tokens: 30
      token-ratio: 0.2

inventory-grpc-service:
  server:
    host: localhost
    port: 6568
  deadline-ms: 10000
  retry:
    enabled: true
    max-attempts: 5
    initial-backoff: 0.2s
    max-backoff: 2s
    backoff-multiplier: 1.7
    retryable-status-codes:
      - UNAVAILABLE
      - RESOURCE_EXHAUSTED
      - DEADLINE_EXCEEDED
      - INTERNAL
    throttling:
      enabled: true
      max-tokens: 30
      token-ratio: 0.2

springdoc:
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
  api-docs:
    path: /api-docs

resilience4j:
  ratelimiter:
    configs:
      grpc_rps:
        limit-for-period: 1000
        limit-refresh-period: 1s
        timeout-duration: 0s
      grpc_rpm:
        limit-for-period: 60000
        limit-refresh-period: 1m
        timeout-duration: 0s
    instances:
      grpc_equipment_rps:
        base-config: grpc_rps
      grpc_equipment_rpm:
        base-config: grpc_rpm
      grpc_inventory_rps:
        base-config: grpc_rps
      grpc_inventory_rpm:
        base-config: grpc_rpm
      grpc_market_rps:
        base-config: grpc_rps
      grpc_market_rpm:
        base-config: grpc_rpm
      grpc_player_rps:
        base-config: grpc_rps
      grpc_player_rpm:
        base-config: grpc_rpm

equipment-grpc-pool:
  properties:
    max-threads: 20
    max-queued-tasks: 1000
    thread-name-prefix: "grpc-equipment"

inventory-grpc-pool:
  properties:
    max-threads: 20
    max-queued-tasks: 1000
    thread-name-prefix: "grpc-inventory"

market-grpc-pool:
  properties:
    max-threads: 20
    max-queued-tasks: 1000
    thread-name-prefix: "grpc-market"

player-grpc-pool:
  properties:
    max-threads: 20
    max-queued-tasks: 1000
    thread-name-prefix: "grpc-player"

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true