syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.inventory.protobuf.inventory.log;

option java_multiple_files = true;

import "common/common.proto";
import "inventory/datatypes.proto";
import "equipment-shared-contract/contract.proto";

enum OperationType {
  OPERATION_TYPE_UNSPECIFIED = 0;
  ADMIN_GIVE = 1;
  ADMIN_TAKE_AWAY = 2;
  SPEND = 3;
  BUY = 4;
  GIVE_AWARD = 5;
  SYSTEM_INVENTORY_INIT = 6;
  ADMIN_INVENTORY_INIT = 7;
}

message PlayerInventoryLogEntry {
  string player_uuid = 1;
  equipment.contract.EquipmentType equipment_type = 2;
  int32 equipment_id = 3;
  OperationType operation_type = 4;
  int32 amount_before = 5;
  int32 amount_after = 6;
  string uuid = 7;
  int64 timestamp = 8;
  optional string operation_uuid = 9;
}

message PlayerInventoryLogPage {
  repeated PlayerInventoryLogEntry data = 1;
  common.protobuf.PaginationInfo pagination_info = 2;
}

message GetPlayerInventoryLogRequest {
  optional common.protobuf.PaginationRequest pagination_request = 1;
  string player_uuid = 2;
}