syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.equipment.protobuf.ammunition;

option java_multiple_files = true;

import "equipment/gun/datatypes.proto";
import "equipment/ammunition/imported_datatypes.proto";
import "common/common.proto";

message AmmunitionInfo {
  int32 id = 1;
  bool enabled = 2;
  string name = 3;
  int32 speed = 4;
  int32 damageMeanValue = 5;
  int32 damageVariance = 6;
  repeated gun.GunReducedInfo compatibleGuns = 7;
  int64 createdTimestamp = 8;
  int64 updatedTimestamp = 9;
}

message AmmunitionInfoListPage {
  repeated AmmunitionInfo data = 1;
  ru.otus.courses.java.advanced.shooter.server.common.protobuf.PaginationInfo paginationInfo = 2;
}

message CreateAmmunitionRequest {
  AmmunitionWritableData data = 1;
}

message UpdateAmmunitionRequest {
  int32 ammunitionId = 1;
  AmmunitionWritableData data = 2;
}

message AmmunitionWritableData {
  bool enabled = 1;
  string name = 2;
  int32 speed = 3;
  int32 damageMeanValue = 4;
  int32 damageVariance = 5;
  repeated int32 compatibleGunIds = 6;
}

message GetAmmunitionRequest {
  int32 ammunitionId = 1;
}

message GetEnabledAmmunitionRequest {
  int32 ammunitionId = 1;
}

message GetAmmunitionListRequest {
  optional common.protobuf.PaginationRequest paginationRequest = 1;
  optional AmmunitionFilter filter = 2;
  optional common.protobuf.RelatedEntitiesInclusionMode compatibleGunsInclusionMode = 3;
}

message AmmunitionFilter {
  optional bool enabled = 1;
  optional string name = 2;
  repeated int32 compatibleGunId = 3;
  optional bool onlyEnabledCompatibleGuns = 4;
  repeated int32 ammunitionId = 5;
}