syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.market.protobuf.trade;

option java_multiple_files = true;

import "common/common.proto";
import "market/product/datatypes.proto";
import "market/money-bundle/datatypes.proto";

enum ProductTradeStatus {
  PT_CREATED = 0;
  PT_WRITE_OFF_WAIT = 1;
  PT_WRITE_OFF_PENDING = 2;
  PT_WRITE_OFF_DONE = 3;
  PT_ISSUE_EQUIPMENT_PENDING = 4;
  PT_ISSUE_EQUIPMENT_DONE = 5;
  PT_SUCCEEDED = 6;
  PT_FAILED = 7;
}

enum MoneyBundleTradeStatus {
  MBT_CREATED = 0;
  MBT_PAYMENT_PENDING = 1;
  MBT_SUCCEEDED = 2;
  MBT_FAILED = 3;
}

message CreateProductTradeRequest {
  int32 playerId = 1;
  int32 productId = 2;
}

message ProductTradeInfo {
  int32 tradeId = 1;
  int32 playerId = 2;
  int32 productId = 3;
  product.ProductEquipmentType equipmentType = 4;
  int32 equipmentId = 5;
  int32 equipmentAmount = 6;
  int32 priceCurrencyId = 7;
  int32 priceValue = 8;
  int64 createdTimestamp = 9;
  int64 updatedTimestamp = 10;
  ProductTradeStatus status = 11;
  string uuid = 12;
}

message ProductTradeInfoListPage {
  repeated ProductTradeInfo data = 1;
  common.protobuf.PaginationInfo paginationInfo = 2;
}

message GetProductTradeRequest {
  int32 tradeId = 1;
  int32 playerId = 2;
}

message GetProductTradesRequest {
  optional common.protobuf.PaginationRequest paginationRequest = 1;
  optional Filter filter = 2;

  message Filter {
    optional int32 playerId = 1;
    repeated int32 tradeIds = 2;
    repeated int32 productIds = 3;
    optional product.ProductEquipmentType equipmentType = 4;
    repeated int32 equipmentIds = 5;
    repeated ProductTradeStatus statuses = 6;
  }
}

message MoneyBundleTradeInfo {
  int32 tradeId = 1;
  int32 playerId = 2;
  int32 moneyBundleId = 3;
  int32 currencyId = 4;
  int32 currencyAmount = 5;
  int32 rublesPrice = 6;
  int64 createdTimestamp = 7;
  int64 updatedTimestamp = 8;
  MoneyBundleTradeStatus status = 9;
  string uuid = 10;
  optional PaymentInfo paymentInfo = 11;

  message PaymentInfo {
    string session = 1;
    string publicToken = 2;
    string uuid = 3;
    int64 startTimestamp = 4;
    optional int64 finishTimestamp = 5;
  }
}

message CreateMoneyBundleTradeRequest {
  int32 playerId = 1;
  int32 moneyBundleId = 2;
}

message MakeMoneyBundleTradePaymentRequest {
  int32 playerId = 1;
  string playerEmail = 2;
  int32 tradeId = 3;
}

message MoneyBundleTradeInfoListPage {
  repeated MoneyBundleTradeInfo data = 1;
  common.protobuf.PaginationInfo paginationInfo = 2;
}

message GetMoneyBundleTradeRequest {
  int32 tradeId = 1;
  int32 playerId = 2;
}

message GetMoneyBundleTradesRequest {
  optional common.protobuf.PaginationRequest paginationRequest = 1;
  optional Filter filter = 2;

  message Filter {
    optional int32 playerId = 1;
    repeated int32 tradeIds = 2;
    repeated int32 moneyBundleIds = 3;
    repeated int32 currencyIds = 4;
    repeated MoneyBundleTradeStatus statuses = 5;
  }
}