syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.market.protobuf.trade;

option java_multiple_files = true;

import "market/trade/datatypes.proto";
import "google/protobuf/empty.proto";

service MoneyBundleTradeServiceAPI {
  rpc CreateMoneyBundleTrade(CreateMoneyBundleTradeRequest) returns (MoneyBundleTradeInfo);
  rpc MakeMoneyBundleTradePayment(MakeMoneyBundleTradePaymentRequest) returns (MoneyBundleTradeInfo);
  rpc GetMoneyBundleTrade(GetMoneyBundleTradeRequest) returns (MoneyBundleTradeInfo);
  rpc GetMoneyBundleTrades(GetMoneyBundleTradesRequest) returns (MoneyBundleTradeInfoListPage);
}

service ProductTradeServiceAPI {
  rpc CreateProductTrade(CreateProductTradeRequest) returns (ProductTradeInfo);
  rpc GetProductTrade(GetProductTradeRequest) returns (ProductTradeInfo);
  rpc GetProductTrades(GetProductTradesRequest) returns (ProductTradeInfoListPage);
}