syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.inventory.protobuf.inventory;

option java_multiple_files = true;

import "common/common.proto";
import "equipment-shared-contract/contract.proto";

message PlayerInventoryItemInfo {
  equipment.contract.EquipmentType equipmentType = 1;
  int32 equipmentId = 2;
  int32 amount = 3;
}

message PlayerInventoryItemsPage {
  repeated PlayerInventoryItemInfo data = 1;
  common.protobuf.PaginationInfo paginationInfo = 2;
}

message GetPlayerInventoryRequest {
  optional common.protobuf.PaginationRequest paginationRequest = 1;
  int32 playerId = 2;
  repeated equipment.contract.EquipmentType types = 3;
}

message InitializePlayerInventoryRequest {
  int32 playerId = 1;
}

message PlayerEquipmentOperationRequest {
  int32 playerId = 1;
  equipment.contract.EquipmentType equipmentType = 2;
  int32 equipmentId = 3;
  int32 amount = 4;
}