syntax = "proto3";

package ru.otus.courses.java.advanced.shooter.server.inventory.protobuf.inventory;

option java_multiple_files = true;

import "common/common.proto";
import "equipment-shared-contract/contract.proto";

message PlayerInventoryItemInfo {
  equipment.contract.EquipmentType equipmentType = 1;
  int32 equipment_id = 2;
  int32 amount = 3;
}

message PlayerInventoryItemsPage {
  repeated PlayerInventoryItemInfo data = 1;
  common.protobuf.PaginationInfo paginationInfo = 2;
}

message GetPlayerInventoryRequest {
  string player_uuid = 1;
  optional Filter filter = 2;
  optional common.protobuf.PaginationRequest pagination_request = 3;

  message Filter {
    optional bool enabled = 1;
    repeated equipment.contract.EquipmentType types = 2;
  }
}

message InitializePlayerInventoryRequest {
  string player_uuid = 1;
}

message PlayerEquipmentOperationRequest {
  string player_uuid = 1;
  equipment.contract.EquipmentType equipmentType = 2;
  int32 equipment_id = 3;
  int32 amount = 4;
}